version: '3'
services:
  web:
    volumes:
      - '../../../app:/opt/node_app/app'
      - '../../../lib:/opt/node_app/lib'
      - '../../../views:/opt/node_app/views'
      - '../../../public:/opt/node_app/public'
      - '../../../extensions:/opt/node_app/extensions'
    ports:
      - '8100:3000'
    restart: always
    stdin_open: true
    tty: true
    build:
      context: ../../../
      dockerfile: .wappler/targets/Development/web/Dockerfile
    depends_on:
      - db
  db:
    image: 'mariadb:10.5'
    environment:
      MYSQL_ROOT_PASSWORD: wK0rt9Ke
      MYSQL_DATABASE: test_multi-insert
      MYSQL_USER: db_user
      MYSQL_PASSWORD: UcfVTXN0
    volumes:
      - './db_init:/docker-entrypoint-initdb.d'
    ports:
      - '9906:3306'
    restart: always
